# Generated by Django 4.1.1 on 2023-10-10 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
